### ISSUE TITLE
it is possible to search by lat and long?

### ISSUE THREAD

**Issue by gomonkey** [Kolyunya/yii2-map-input-widget#15]
Hello how can I searching not for place but for latitude and longitude?

thanks

**Comment by gomonkey** [comment]
wao... not answer after a week

**Comment by Kolyunya** [comment]
> Hello how can I searching not for place but for latitude and longitude?
You can not.

**Comment by gomonkey** [comment]
oh really?? that is weird because i did it right now by myself.

I am putting here my code, you can use if you want and improve it, i did it in 10 minutes

map-input-widget.js
line below: 122 

```javascript
google.maps.event.addDomListener(document, 'keyup', function(e) {
	var code = (e.keyCode ? e.keyCode : e.which);
	if (code === 13) {
		var latAndLong = $('.kolyunya-map-input-widget-search-bar').val();
		var parts = latAndLong.split(",")
		self.setPosition({
			latitude: parts[0],
			longitude: parts[1],
		});
	}
});
`
