### ISSUE TITLE
how to install it through composer

### ISSUE THREAD

**Issue by asifrafeeq** [Kolyunya/yii2-map-input-widget#17]
nice widget, but how to install it through composer. ?

**Comment by Kolyunya** [comment]
@asifrafeeq as any other composer package. The package name is `kolyunya/yii2-map-input-widget`.

**Comment by asifrafeeq** [comment]
Thanks a lot dear. ☺


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nikolay Oleynikov <notifications@github.com> Date: 7/19/17  2:39 PM  (GMT+04:00) To: Kolyunya/yii2-map-input-widget <yii2-map-input-widget@noreply.github.com> Cc: Asif Ullah Khan <asifrafeeq1@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [Kolyunya/yii2-map-input-widget] how to install it through
  composer (#17) 
@asifrafeeq as any other composer package. The package name is kolyunya/yii2-map-input-widget.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Kolyunya/yii2-map-input-widget","title":"Kolyunya/yii2-map-input-widget","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Kolyunya/yii2-map-input-widget"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kolyunya in #17: @asifrafeeq as any other composer package. The package name is `kolyunya/yii2-map-input-widget`."}],"action":{"name":"View Issue","url":"https://github.com/Kolyunya/yii2-map-input-widget/issues/17#issuecomment-316345160"}}}
