### ISSUE TITLE
Is there a possibility to add a searchbar to the map?

### ISSUE THREAD

**Issue by HannibalSmith13** [Kolyunya/yii2-map-input-widget#5]
Is there any simple possibility to add a searchbar to the map?

Like in this example: https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

Searching only with the cursor is horrible and i've no idea how to implement that example into your widget.

Thanks :)

**Comment by maxxer** [comment]
@HannibalSmith13 did you ever implement this? I need it too. thanks

**Comment by Kolyunya** [comment]
Implemented in d4f3243d3da743d7447047335d8da5a4b58a3f7f
