### ISSUE TITLE
Embedding 'SEARCH' in Map

### ISSUE THREAD

**Issue by abrahamgeorgec** [Kolyunya/yii2-map-input-widget#8]
Hi Kolyunya

Thanks for the widget. 

Can we extend to have a provision to embed "search" within map.
Usecase: 
#1 User first search a place (or close by place)
#2  Map then moves to this new coordinates
#3 User Drags the marker for fine tuning location.

Warm Regards
Abraham

**Comment by Kolyunya** [comment]
@abrahamgeorgec sure, feel free to make a pull request or fork.
